# Generated by Django 4.2.26 on 2025-11-27 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entries', '0001_initial'),
        ('competitions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Heat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heat_number', models.PositiveIntegerField(verbose_name='組番号')),
                ('scheduled_start_time', models.TimeField(blank=True, null=True, verbose_name='開始予定時刻')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('is_finalized', models.BooleanField(default=False, verbose_name='確定済み')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heats', to='competitions.race', verbose_name='種目')),
            ],
            options={
                'verbose_name': '組',
                'verbose_name_plural': '組',
                'ordering': ['race', 'heat_number'],
                'unique_together': {('race', 'heat_number')},
            },
        ),
        migrations.CreateModel(
            name='HeatAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bib_number', models.PositiveIntegerField(verbose_name='腰ナンバー')),
                ('status', models.CharField(choices=[('assigned', '出走予定'), ('dns', '欠場（DNS）'), ('dnf', '途中棄権（DNF）'), ('dq', '失格（DQ）')], default='assigned', max_length=10, verbose_name='ステータス')),
                ('checked_in', models.BooleanField(default=False, verbose_name='点呼済み')),
                ('checked_in_at', models.DateTimeField(blank=True, null=True, verbose_name='点呼時刻')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='heat_assignment', to='entries.entry', verbose_name='エントリー')),
                ('heat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='heats.heat', verbose_name='組')),
            ],
            options={
                'verbose_name': '組編成',
                'verbose_name_plural': '組編成',
                'ordering': ['heat', 'bib_number'],
                'unique_together': {('heat', 'bib_number'), ('heat', 'entry')},
            },
        ),
    ]
