# Generated by Django 4.2.26 on 2025-11-27 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='heatassignment',
            name='race_bib_number',
            field=models.PositiveIntegerField(blank=True, help_text='大会全体で一意のゼッケン番号', null=True, verbose_name='ゼッケン番号'),
        ),
    ]
