# Generated by Django 4.2.26 on 2025-11-27 03:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import payments.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('entries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=100, verbose_name='銀行名')),
                ('branch_name', models.CharField(max_length=100, verbose_name='支店名')),
                ('account_type', models.CharField(choices=[('ordinary', '普通'), ('current', '当座')], default='ordinary', max_length=10, verbose_name='口座種別')),
                ('account_number', models.CharField(max_length=20, verbose_name='口座番号')),
                ('account_holder', models.CharField(max_length=100, verbose_name='口座名義')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
            ],
            options={
                'verbose_name': '振込先口座',
                'verbose_name_plural': '振込先口座',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_image', models.ImageField(help_text='振込完了後、振込明細書またはネットバンキングのスクリーンショットをアップロードしてください', upload_to=payments.models.payment_image_path, verbose_name='振込明細画像')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='振込日')),
                ('payment_amount', models.PositiveIntegerField(blank=True, null=True, verbose_name='振込金額')),
                ('payer_name', models.CharField(blank=True, max_length=100, verbose_name='振込名義')),
                ('status', models.CharField(choices=[('pending', '確認待ち'), ('approved', '承認済み'), ('rejected', '却下')], default='pending', max_length=20, verbose_name='ステータス')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='確認日時')),
                ('review_note', models.TextField(blank=True, verbose_name='確認メモ')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='アップロード日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('entry_group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='entries.entrygroup', verbose_name='エントリーグループ')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_payments', to=settings.AUTH_USER_MODEL, verbose_name='確認者')),
            ],
            options={
                'verbose_name': '入金情報',
                'verbose_name_plural': '入金情報',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
