# Generated by Django 4.2.26 on 2025-11-27 06:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_add_ncg_standard_time_nationality'),
        ('competitions', '0003_add_ncg_standard_time_nationality'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_large_bus', models.PositiveIntegerField(default=0, help_text='大型バス（45人以上乗り）の希望台数', verbose_name='大型バス希望数')),
                ('requested_medium_bus', models.PositiveIntegerField(default=0, help_text='マイクロバス・中型バスの希望台数', verbose_name='中型バス希望数')),
                ('requested_car', models.PositiveIntegerField(default=0, help_text='普通乗用車の希望台数', verbose_name='乗用車希望数')),
                ('request_note', models.TextField(blank=True, help_text='駐車に関する要望があれば記入してください', verbose_name='備考・連絡事項')),
                ('status', models.CharField(choices=[('requested', '申請中'), ('assigned', '割当済'), ('rejected', '却下')], default='requested', max_length=20, verbose_name='ステータス')),
                ('assigned_parking_lot', models.CharField(blank=True, help_text='例: A駐車場、第2グラウンド横', max_length=100, verbose_name='割当駐車場')),
                ('assigned_large_bus', models.PositiveIntegerField(default=0, verbose_name='大型バス割当数')),
                ('assigned_medium_bus', models.PositiveIntegerField(default=0, verbose_name='中型バス割当数')),
                ('assigned_car', models.PositiveIntegerField(default=0, verbose_name='乗用車割当数')),
                ('entry_time', models.TimeField(blank=True, help_text='許可される入庫開始時間', null=True, verbose_name='入庫時間')),
                ('exit_time', models.TimeField(blank=True, help_text='出庫期限時間', null=True, verbose_name='出庫時間')),
                ('assignment_note', models.TextField(blank=True, help_text='割当に関する注意事項など', verbose_name='管理者メモ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='申請日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parking_requests', to='competitions.competition', verbose_name='大会')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parking_requests', to='accounts.organization', verbose_name='団体')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parking_requests', to=settings.AUTH_USER_MODEL, verbose_name='申込者')),
            ],
            options={
                'verbose_name': '駐車場申請',
                'verbose_name_plural': '駐車場申請',
                'ordering': ['-created_at'],
                'unique_together': {('organization', 'competition')},
            },
        ),
    ]
