# Generated by Django 4.2.26 on 2025-11-27 07:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='タイトル')),
                ('body', models.TextField(verbose_name='本文')),
                ('category', models.CharField(choices=[('info', 'お知らせ'), ('important', '重要'), ('correction', '訂正'), ('urgent', '緊急')], default='info', max_length=20, verbose_name='カテゴリ')),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='公開日時')),
                ('is_active', models.BooleanField(default=True, verbose_name='公開中')),
                ('is_important', models.BooleanField(default=False, help_text='ONにすると赤色で目立つ表示になります', verbose_name='重要なお知らせ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': 'お知らせ',
                'verbose_name_plural': 'お知らせ',
                'ordering': ['-published_at'],
            },
        ),
    ]
