# Generated by Django 4.2.26 on 2025-11-27 03:51

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='メールアドレス')),
                ('full_name', models.CharField(max_length=100, verbose_name='氏名')),
                ('full_name_kana', models.CharField(max_length=100, verbose_name='フリガナ')),
                ('phone', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^[\\d-]+$', '電話番号は数字とハイフンのみ使用できます')], verbose_name='電話番号')),
                ('is_admin', models.BooleanField(default=False, verbose_name='管理者権限')),
                ('is_individual', models.BooleanField(default=False, verbose_name='個人参加')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
            ],
            options={
                'verbose_name': 'ユーザー',
                'verbose_name_plural': 'ユーザー',
                'ordering': ['full_name_kana'],
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='団体名')),
                ('name_kana', models.CharField(max_length=100, verbose_name='団体名（フリガナ）')),
                ('short_name', models.CharField(blank=True, max_length=20, verbose_name='略称')),
                ('representative_name', models.CharField(max_length=100, verbose_name='代表者氏名')),
                ('representative_email', models.EmailField(max_length=254, verbose_name='代表者メールアドレス')),
                ('representative_phone', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^[\\d-]+$', '電話番号は数字とハイフンのみ使用できます')], verbose_name='代表者電話番号')),
                ('postal_code', models.CharField(blank=True, max_length=8, verbose_name='郵便番号')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='住所')),
                ('jaaf_code', models.CharField(blank=True, max_length=20, verbose_name='陸連登録コード')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
            ],
            options={
                'verbose_name': '団体',
                'verbose_name_plural': '団体',
                'ordering': ['name_kana'],
            },
        ),
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=50, verbose_name='姓')),
                ('first_name', models.CharField(max_length=50, verbose_name='名')),
                ('last_name_kana', models.CharField(max_length=50, verbose_name='姓（カナ）')),
                ('first_name_kana', models.CharField(max_length=50, verbose_name='名（カナ）')),
                ('gender', models.CharField(choices=[('M', '男子'), ('F', '女子')], max_length=1, verbose_name='性別')),
                ('birth_date', models.DateField(verbose_name='生年月日')),
                ('jaaf_id', models.CharField(blank=True, max_length=20, verbose_name='陸連登録番号')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='athletes', to='accounts.organization', verbose_name='所属団体')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='athletes', to=settings.AUTH_USER_MODEL, verbose_name='登録ユーザー')),
            ],
            options={
                'verbose_name': '選手',
                'verbose_name_plural': '選手',
                'ordering': ['last_name_kana', 'first_name_kana'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='accounts.organization', verbose_name='所属団体'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
