# Generated by Django 4.2.26 on 2025-11-27 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='nationality',
            field=models.CharField(default='JPN', help_text='IOC国コード（3文字）。例: JPN, USA, KEN', max_length=3, verbose_name='国籍'),
        ),
    ]
