# Generated by Django 4.2.26 on 2025-11-27 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_add_ncg_standard_time_nationality'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=200, verbose_name='住所'),
        ),
        migrations.AddField(
            model_name='user',
            name='affiliation_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='所属団体略称'),
        ),
        migrations.AddField(
            model_name='user',
            name='coach_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='監督名'),
        ),
        migrations.AddField(
            model_name='user',
            name='contact_person',
            field=models.CharField(blank=True, max_length=100, verbose_name='連絡責任者名'),
        ),
        migrations.AddField(
            model_name='user',
            name='organization_type',
            field=models.CharField(choices=[('university', '大学'), ('highschool', '高校'), ('club', 'クラブ'), ('individual', '個人'), ('other', 'その他')], default='individual', max_length=20, verbose_name='団体分類'),
        ),
        migrations.AddField(
            model_name='user',
            name='postal_code',
            field=models.CharField(blank=True, max_length=8, verbose_name='郵便番号'),
        ),
    ]
