# Generated by Django 4.2.26 on 2025-11-27 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_add_user_registration_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='first_name_en',
            field=models.CharField(blank=True, max_length=50, verbose_name='名（ローマ字）'),
        ),
        migrations.AddField(
            model_name='athlete',
            name='grade',
            field=models.CharField(blank=True, choices=[('', '---'), ('1', '1年'), ('2', '2年'), ('3', '3年'), ('4', '4年'), ('M1', '修士1年'), ('M2', '修士2年'), ('D1', '博士1年'), ('D2', '博士2年'), ('D3', '博士3年')], max_length=5, verbose_name='学年'),
        ),
        migrations.AddField(
            model_name='athlete',
            name='last_name_en',
            field=models.CharField(blank=True, max_length=50, verbose_name='姓（ローマ字）'),
        ),
        migrations.AddField(
            model_name='athlete',
            name='registered_pref',
            field=models.CharField(default='', help_text='例: 東京、神奈川', max_length=10, verbose_name='登録陸協'),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='名（漢字）'),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='jaaf_id',
            field=models.CharField(default='', help_text='陸連登録番号（公認申請に必須）', max_length=20, verbose_name='JAAF ID'),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='姓（漢字）'),
        ),
    ]
