# Generated by Django 4.2.26 on 2025-11-27 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_add_athlete_jaaf_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='organization_type',
            field=models.CharField(choices=[('university', '大学'), ('highschool', '高校'), ('corporate', '実業団'), ('club', 'クラブ'), ('other', 'その他')], default='individual', max_length=20, verbose_name='団体分類'),
        ),
    ]
