# Generated by Django 4.2.26 on 2025-11-29 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_update_organization_type_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='birth_date',
            field=models.DateField(help_text='形式: YYYY-MM-DD（例: 2000-04-01）', verbose_name='生年月日'),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='first_name',
            field=models.CharField(help_text='例: 太郎', max_length=50, verbose_name='名（漢字）'),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='first_name_en',
            field=models.CharField(blank=True, help_text='先頭のみ大文字。例: Taro', max_length=50, verbose_name='名（ローマ字）'),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='first_name_kana',
            field=models.CharField(help_text='全角カタカナで入力。例: タロウ', max_length=50, verbose_name='名（カナ）'),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='gender',
            field=models.CharField(choices=[('M', '男子'), ('F', '女子')], help_text='男子または女子を選択', max_length=1, verbose_name='性別'),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='grade',
            field=models.CharField(blank=True, choices=[('', '---'), ('1', '1年'), ('2', '2年'), ('3', '3年'), ('4', '4年'), ('M1', '修士1年'), ('M2', '修士2年'), ('D1', '博士1年'), ('D2', '博士2年'), ('D3', '博士3年')], help_text='学生の場合は学年を選択。社会人は空欄のOK', max_length=5, verbose_name='学年'),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='last_name',
            field=models.CharField(help_text='例: 山田', max_length=50, verbose_name='姓（漢字）'),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='last_name_en',
            field=models.CharField(blank=True, help_text='大文字で入力。例: YAMADA', max_length=50, verbose_name='姓（ローマ字）'),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='last_name_kana',
            field=models.CharField(help_text='全角カタカナで入力。例: ヤマダ', max_length=50, verbose_name='姓（カナ）'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(help_text='正式名称で入力。例: 日本体育大学', max_length=100, unique=True, verbose_name='団体名'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name_kana',
            field=models.CharField(help_text='全角カタカナで入力。例: ニッポンタイイクダイガク', max_length=100, verbose_name='団体名（フリガナ）'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='short_name',
            field=models.CharField(blank=True, help_text='短縮名。例: 日体大、早稲田、中大', max_length=20, verbose_name='略称'),
        ),
    ]
