# Generated by Django 4.2.26 on 2025-11-29 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_athlete_birth_date_alter_athlete_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='nationality',
            field=models.CharField(choices=[('JPN', '日本 (JPN)'), ('KEN', 'ケニア (KEN)'), ('ETH', 'エチオピア (ETH)'), ('KOR', '韓国 (KOR)'), ('CHN', '中国 (CHN)'), ('USA', 'アメリカ (USA)'), ('GBR', 'イギリス (GBR)'), ('UGA', 'ウガンダ (UGA)'), ('TAN', 'タンザニア (TAN)'), ('MAR', 'モロッコ (MAR)')], default='JPN', help_text='IOC国コード（3文字）', max_length=3, verbose_name='国籍'),
        ),
    ]
