# Generated by Django 4.2.26 on 2025-11-27 03:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('competitions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('csv_startlist', 'スタートリストCSV'), ('pdf_rollcall', '点呼用PDF'), ('pdf_program', 'プログラム原稿PDF'), ('pdf_all', '全データPDF')], max_length=20, verbose_name='帳票種別')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='出力日時')),
                ('file_path', models.CharField(blank=True, max_length=500, verbose_name='ファイルパス')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_logs', to='competitions.competition', verbose_name='大会')),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_logs', to=settings.AUTH_USER_MODEL, verbose_name='出力者')),
                ('race', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_logs', to='competitions.race', verbose_name='種目')),
            ],
            options={
                'verbose_name': '帳票出力ログ',
                'verbose_name_plural': '帳票出力ログ',
                'ordering': ['-generated_at'],
            },
        ),
    ]
