# Generated by Django 4.2.26 on 2025-11-27 03:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('competitions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('declared_time', models.DecimalField(decimal_places=2, help_text='例: 14分30秒00 → 870.00', max_digits=8, verbose_name='申告タイム（秒）')),
                ('personal_best', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='自己ベスト（秒）')),
                ('status', models.CharField(choices=[('pending', '申込中（入金待ち）'), ('payment_uploaded', '入金確認待ち'), ('confirmed', '確定'), ('cancelled', 'キャンセル'), ('dns', '欠場（DNS）')], default='pending', max_length=20, verbose_name='ステータス')),
                ('note', models.TextField(blank=True, verbose_name='備考')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='申込日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='accounts.athlete', verbose_name='選手')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='competitions.race', verbose_name='種目')),
                ('registered_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registered_entries', to=settings.AUTH_USER_MODEL, verbose_name='申込者')),
            ],
            options={
                'verbose_name': 'エントリー',
                'verbose_name_plural': 'エントリー',
                'ordering': ['race', 'declared_time'],
                'unique_together': {('athlete', 'race')},
            },
        ),
        migrations.CreateModel(
            name='EntryGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.PositiveIntegerField(default=0, verbose_name='合計金額')),
                ('status', models.CharField(choices=[('pending', '入金待ち'), ('payment_uploaded', '入金確認待ち'), ('confirmed', '確定'), ('cancelled', 'キャンセル')], default='pending', max_length=20, verbose_name='ステータス')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='申込日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entry_groups', to='competitions.competition', verbose_name='大会')),
                ('entries', models.ManyToManyField(related_name='entry_groups', to='entries.entry', verbose_name='エントリー')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entry_groups', to='accounts.organization', verbose_name='団体')),
                ('registered_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entry_groups', to=settings.AUTH_USER_MODEL, verbose_name='申込者')),
            ],
            options={
                'verbose_name': 'エントリーグループ',
                'verbose_name_plural': 'エントリーグループ',
                'ordering': ['-created_at'],
            },
        ),
    ]
