# Generated by Django 4.2.26 on 2025-11-27 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0003_add_ncg_standard_time_nationality'),
        ('entries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='moved_from_ncg',
            field=models.BooleanField(default=False, help_text='NCG定員超過により一般種目に移動された場合True', verbose_name='NCGから移動'),
        ),
        migrations.AddField(
            model_name='entry',
            name='original_ncg_race',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moved_entries', to='competitions.race', verbose_name='元NCG種目'),
        ),
    ]
