# Generated by Django 4.2.26 on 2025-11-29 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0005_alter_competition_default_heat_capacity_and_more'),
        ('accounts', '0006_alter_athlete_birth_date_alter_athlete_first_name_and_more'),
        ('entries', '0002_add_ncg_standard_time_nationality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='athlete',
            field=models.ForeignKey(help_text='エントリーする選手を選択してください', on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='accounts.athlete', verbose_name='選手'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='declared_time',
            field=models.DecimalField(decimal_places=2, help_text='秒単位で入力（右の分秒表示を参考に）', max_digits=8, verbose_name='申告タイム（秒）'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='note',
            field=models.TextField(blank=True, help_text='特記事項があれば入力（任意）', verbose_name='備考'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='personal_best',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='秒単位で入力（任意）', max_digits=8, null=True, verbose_name='自己ベスト（秒）'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='race',
            field=models.ForeignKey(help_text='出場する種目を選択してください', on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='competitions.race', verbose_name='種目'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='status',
            field=models.CharField(choices=[('pending', '申込中（入金待ち）'), ('payment_uploaded', '入金確認待ち'), ('confirmed', '確定'), ('cancelled', 'キャンセル'), ('dns', '欠場（DNS）')], default='pending', help_text='入金確認後に「確定」に変更してください', max_length=20, verbose_name='ステータス'),
        ),
    ]
