# Generated by Django 4.2.26 on 2025-12-19 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0003_alter_entry_athlete_alter_entry_declared_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrygroup',
            name='is_draft',
            field=models.BooleanField(default=True, help_text='一時保存の場合はTrue、確定処理後はFalse', verbose_name='下書き'),
        ),
    ]
