# Generated by Django 4.2.26 on 2025-11-27 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='大会名')),
                ('description', models.TextField(blank=True, verbose_name='大会説明')),
                ('event_date', models.DateField(verbose_name='開催日')),
                ('venue', models.CharField(default='日本体育大学横浜・健志台キャンパス陸上競技場', max_length=200, verbose_name='会場')),
                ('entry_start_at', models.DateTimeField(verbose_name='エントリー開始日時')),
                ('entry_end_at', models.DateTimeField(verbose_name='エントリー締切日時')),
                ('entry_fee', models.PositiveIntegerField(default=1000, verbose_name='参加費（円）')),
                ('default_heat_capacity', models.PositiveIntegerField(default=40, verbose_name='1組あたりの定員（デフォルト）')),
                ('is_published', models.BooleanField(default=False, verbose_name='公開中')),
                ('is_entry_open', models.BooleanField(default=False, verbose_name='エントリー受付中')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': '大会',
                'verbose_name_plural': '大会',
                'ordering': ['-event_date'],
            },
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.PositiveIntegerField(choices=[(800, '800m'), (1500, '1500m'), (3000, '3000m'), (5000, '5000m'), (10000, '10000m')], verbose_name='距離（m）')),
                ('gender', models.CharField(choices=[('M', '男子'), ('F', '女子'), ('X', '混合')], max_length=1, verbose_name='性別区分')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='種目名')),
                ('heat_capacity', models.PositiveIntegerField(default=40, verbose_name='1組あたりの定員')),
                ('max_entries', models.PositiveIntegerField(blank=True, default=200, null=True, verbose_name='エントリー上限')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='表示順')),
                ('scheduled_start_time', models.TimeField(blank=True, null=True, verbose_name='開始予定時刻')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='races', to='competitions.competition', verbose_name='大会')),
            ],
            options={
                'verbose_name': '種目',
                'verbose_name_plural': '種目',
                'ordering': ['display_order', 'distance'],
                'unique_together': {('competition', 'distance', 'gender')},
            },
        ),
    ]
