# Generated by Django 4.2.26 on 2025-11-27 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='race',
            unique_together={('competition', 'name')},
        ),
    ]
