# Generated by Django 4.2.26 on 2025-11-27 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0002_change_race_unique_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='fallback_race',
            field=models.ForeignKey(blank=True, help_text='NCG定員超過時に選手を移動する一般種目', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ncg_source', to='competitions.race', verbose_name='一般種目（NCG溢れ移動先）'),
        ),
        migrations.AddField(
            model_name='race',
            name='is_ncg',
            field=models.BooleanField(default=False, verbose_name='NCG種目'),
        ),
        migrations.AddField(
            model_name='race',
            name='ncg_capacity',
            field=models.PositiveIntegerField(default=35, help_text='NCG組に入れる上位人数', verbose_name='NCG定員'),
        ),
        migrations.AddField(
            model_name='race',
            name='standard_time',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='この記録より遅い申告タイムはエントリー不可。例: 15分30秒 → 930.00', max_digits=8, null=True, verbose_name='参加標準記録（秒）'),
        ),
    ]
