# Generated by Django 4.2.26 on 2025-11-27 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0003_add_ncg_standard_time_nationality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='entry_fee',
            field=models.PositiveIntegerField(default=2000, verbose_name='参加費（円）'),
        ),
    ]
