# Generated by Django 4.2.26 on 2025-11-29 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0004_update_entry_fee_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='default_heat_capacity',
            field=models.PositiveIntegerField(default=40, help_text='種目で個別設定しない場合に使用される定員数', verbose_name='1組あたりの定員（デフォルト）'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='description',
            field=models.TextField(blank=True, help_text='大会の詳細情報や注意事項を記載（任意）', verbose_name='大会説明'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='entry_end_at',
            field=models.DateTimeField(help_text='この日時でエントリー受付を終了します', verbose_name='エントリー締切日時'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='entry_fee',
            field=models.PositiveIntegerField(default=2000, help_text='1人あたりの参加費。例: 2000', verbose_name='参加費（円）'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='entry_start_at',
            field=models.DateTimeField(help_text='この日時からエントリーを受け付けます', verbose_name='エントリー開始日時'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='event_date',
            field=models.DateField(help_text='形式: YYYY-MM-DD', verbose_name='開催日'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='is_entry_open',
            field=models.BooleanField(default=False, help_text='チェックするとエントリーを受け付けます（期間内のみ有効）', verbose_name='エントリー受付中'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='is_published',
            field=models.BooleanField(default=False, help_text='チェックすると参加者から大会が見えるようになります', verbose_name='公開中'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='name',
            field=models.CharField(help_text='例: 第325回日体大長距離競技会', max_length=200, verbose_name='大会名'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='venue',
            field=models.CharField(default='日本体育大学横浜・健志台キャンパス陸上競技場', help_text='開催場所の正式名称', max_length=200, verbose_name='会場'),
        ),
        migrations.AlterField(
            model_name='race',
            name='is_ncg',
            field=models.BooleanField(default=False, help_text='NITTAI CHALLENGE GAMES対象種目', verbose_name='NCG種目'),
        ),
        migrations.AlterField(
            model_name='race',
            name='max_entries',
            field=models.PositiveIntegerField(blank=True, default=50, null=True, verbose_name='エントリー上限'),
        ),
        migrations.AlterField(
            model_name='race',
            name='name',
            field=models.CharField(blank=True, help_text='例: 1組、2組、3組（空欄の場合は自動生成）', max_length=100, verbose_name='種目名'),
        ),
        migrations.AlterField(
            model_name='race',
            name='scheduled_start_time',
            field=models.TimeField(blank=True, help_text='例: 10:30、14:00', null=True, verbose_name='開始予定時刻'),
        ),
    ]
