# Generated by Django 4.2.26 on 2025-11-29 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0005_alter_competition_default_heat_capacity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='name',
            field=models.CharField(blank=True, choices=[('', '（自動生成）'), ('1組', '1組'), ('2組', '2組'), ('3組', '3組'), ('4組', '4組'), ('5組', '5組'), ('6組', '6組'), ('7組', '7組'), ('8組', '8組'), ('9組', '9組'), ('10組', '10組'), ('11組', '11組'), ('12組', '12組'), ('13組', '13組'), ('14組', '14組'), ('15組', '15組'), ('16組', '16組'), ('17組', '17組'), ('18組', '18組'), ('19組', '19組'), ('20組', '20組'), ('21組', '21組'), ('22組', '22組'), ('23組', '23組'), ('24組', '24組'), ('25組', '25組'), ('26組', '26組'), ('27組', '27組'), ('28組', '28組'), ('29組', '29組'), ('30組', '30組')], help_text='空欄の場合は自動生成（例: 男子5000m）', max_length=100, verbose_name='種目名'),
        ),
    ]
