# Generated by Django 4.2.26 on 2025-11-29 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0006_alter_race_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='event_end_date',
            field=models.DateField(blank=True, help_text='2日間以上の大会の場合は最終日を指定（1日開催の場合は空欄）', null=True, verbose_name='開催日（最終日）'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='event_date',
            field=models.DateField(help_text='大会の開始日（形式: YYYY-MM-DD）', verbose_name='開催日（初日）'),
        ),
    ]
