# Generated by Django 4.2.26 on 2025-11-29 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0007_add_event_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='name',
            field=models.CharField(blank=True, help_text='空欄の場合は自動生成（例: 男子5000m）。NCG種目などは手動入力可能', max_length=100, verbose_name='種目名'),
        ),
    ]
